### PR TITLE
Update tsconfig.json

### PR DESCRIPTION
**Pull request by mikemorreale**

### CODE REVIEW

**Comment by Neil-Ni** [comment]
@mikemorreale let me assign this to myself. i was still fixing this issue in the other PR locally

**Comment by matt-casey** [comment]
Do we need to add  "node_modules/@types/**/*.ts", to the filesGlob?

Also, I think the changes I made in the other branch (now in master) mean we can target es5 and still have everything work.

**Comment by mikemorreale** [comment]
In order for TypeScript to work in Atom we need to add that to the filesGlob.

**Comment by mikemorreale** [comment]
No longer needed

**Pull request closed without merging**
